### ISSUE TITLE
I think we do not need coordinator here 

### ISSUE THREAD

**Issue by ko7tya** [b4udie/MDBApi#10]
https://github.com/b4udie/MDBApi/blob/228d870b2fc46b790cd76e3529b512f35b71f273/MDBApi/Providers/ListDataProvider.swift#L21

**Comment by ko7tya** [comment]
По суті координатор відповідає лише за навігацію, а в тебе получається що координатор держить і контроллер і датапровайдер, краще зроби щоб датапровайдер давай команду контроллеру, а він в свою чергу давав команду координатору, таким чином ми зменшим кількість залежностей в датапровайдері

**Comment by b4udie** [comment]
Створив в провайдері 	var listViewController: ListViewController?
В контроллері dataProvider.listViewController = self
І в дав команду контроллеру в didSelectRowAt
	`
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
		listViewController!.coordinator?.checkDetail(movieId: moviesList?.items[indexPath.row].id)
	}
`
