### ISSUE TITLE
Make networking more complex 

### ISSUE THREAD

**Issue by ko7tya** [b4udie/MDBApi#11]
https://github.com/b4udie/MDBApi/blob/228d870b2fc46b790cd76e3529b512f35b71f273/MDBApi/Services/Network.swift#L17
Наприклад дати можливість легко змінити основний роут на інший
Також зробити щоб таск створювався з одного місця, а то по суті в тебе йде дублювання в кожному із запитів 
Зробити кеш

**Comment by b4udie** [comment]
Зробив network layer с прикладу, що знайшов. Не дублюєьтся, а створюється з одного місця. Зробив кеш.
Створив группу Networking в проекті, все це там
