### ISSUE TITLE
Implement caching for images 

### ISSUE THREAD

**Issue by ko7tya** [b4udie/MDBApi#9]
https://github.com/b4udie/MDBApi/blob/228d870b2fc46b790cd76e3529b512f35b71f273/MDBApi/Extensions/UIImageView%2BdownloadImage.swift#L12

**Comment by b4udie** [comment]
`let imageCache = NSCache<AnyObject, AnyObject>()

extension UIImageView {
	
	func cacheImage(from urlString: String) {
		
		guard let url = URL(string: urlString) else { return }
		
		contentMode = .scaleAspectFill
		image = nil
		
		if let imageFromCache = imageCache.object(forKey: urlString as AnyObject) as? UIImage {
			self.image = imageFromCache
			return
		}
		
		URLSession.shared.dataTask(with: url) {
			data, response, error in
			if let response = data {
				DispatchQueue.main.async {
					let imageToCache = UIImage(data: response)
					imageCache.setObject(imageToCache!, forKey: urlString as AnyObject)
					self.image = imageToCache
				}
			}
			}.resume()
	}
	
}
`
